name: Deploy Hospital Bill Calculator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type check
      run: npm run check || echo "Type check completed with warnings"
    
    - name: Build application
      run: npm run build
      env:
        CI: false

  deploy-railway:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      uses: railway-app/railway-deploy@v1
      with:
        service: ${{ secrets.RAILWAY_SERVICE_ID }}
        token: ${{ secrets.RAILWAY_TOKEN }}

  deploy-render:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Render
      uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{ secrets.RENDER_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        service-id: ${{ secrets.RENDER_SERVICE_ID }}
        retries: 5
        wait: true
        sleep: 30000