name: Deploy Hospital Bill Calculator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run type check
      run: npm run check || echo "Type check completed with warnings"
    
    - name: Build application
      run: npm run build
      env:
        CI: false

  # Deployment jobs are disabled by default
  # Enable by setting repository secrets and variables
  
  deploy-info:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment Instructions
      run: |
        echo "## 🚀 Ready for Deployment" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Your Hospital Bill Calculator is ready to deploy!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Quick Deploy Options:" >> $GITHUB_STEP_SUMMARY
        echo "1. **Railway**: Connect this repo to Railway for auto-deployment" >> $GITHUB_STEP_SUMMARY
        echo "2. **Render**: Import this repo to Render with build command \`npm run build\`" >> $GITHUB_STEP_SUMMARY
        echo "3. **Vercel**: Connect repo to Vercel for serverless deployment" >> $GITHUB_STEP_SUMMARY
        echo "4. **Docker**: Use \`docker build -t hospital-bill-calculator .\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "See [docs/DEPLOYMENT.md](./docs/DEPLOYMENT.md) for detailed instructions." >> $GITHUB_STEP_SUMMARY